name: Daily Job Scraper

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 7:30 AM IST (2:00 AM UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./credentials.json
      run: python main.py
